---
- name: Ensure users exist with correct groups
  ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups | join(',') }}"
        append: true
        state: present
  loop: "{{ users }}"
