---
- name: Configure the web server(s) according to specs
  become: true
  hosts: webserver
  vars_files:
    - vars/users.yml
  roles:
    - webserver

- name: Configure the database server(s) according to specs
  become: true
  hosts: dbserver
  vars_files:
    - secrets.yml
  roles:
    - dbserver
